# Generated by Django 5.2.4 on 2025-07-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=25)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
