# Generated by Django 5.2.4 on 2025-07-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
