version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    volumes:
      #- .:/app
      - ./db:/app/db
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=student.settings
    restart: "no"