# Generated by Django 5.2.4 on 2025-07-22 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pais', '0002_pais_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
                ('isActive', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('deleted', models.BooleanField(default=False, verbose_name='¿Eliminado?')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pais.pais', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'ordering': ['descripcion'],
                'unique_together': {('pais', 'codigo')},
            },
        ),
    ]
